Added popular VScode theme Night Owl
PrismJS/prism-themes pull request #115
Opened 2021-03-17 18:09 UTC by SimpleIndian

I also the formatted readme file.
@RunDevelopment , please review these changes.

2021-03-17 19:17 UTC, RunDevelopment requested changes
Thank you for the PR.

I have one comment and then there is licensing. You are not the owner of this theme. @sdras licensed the theme using MIT, so we have to adhere to that license. Please add a comment to the CSS file crediting @sdras along with [these lines](https://github.com/sdras/night-owl-vscode-theme/blob/main/LICENSE#L1-L3) of the license.

2021-03-17 19:17 UTC, RunDevelopment commented on README.md
> -* [__CB__](themes/prism-cb.css) (originally by [C. Bavota](https://bitbucket.org/cbavota), adapted by [atelierbram](https://github.com/atelierbram))<br />
Please revert all formatting changes to this file.

2021-03-18 04:16 UTC, souvik362 commented
@RunDevelopment , Thanks for the generous suggestion . Quickly fixing it.

2021-05-01 12:07 UTC, RunDevelopment commented
I'm really sorry for the delay @SimpleIndian!

LGTM;

2021-05-01 12:07 UTC, RunDevelopment approved these changes

2021-05-01 12:07 UTC, merged