build: add node.js main file
PrismJS/prism-themes pull request #116
Opened 2021-03-23 09:00 UTC by Kikobeats

Hello,

In a previous PR (#114) the `main` field at `package.json` was removed because it was causing not useful.

This PR adds the field again but rather than pointing to a filesystem folder, it's returning the absolute path where the themes are living:

```js
require('prism-themes')
// {
//  folderPath: '/Users/kikobeats/Projects/microlink/browserless/packages/screenshot/node_modules/prism-themes/themes'
// }
```

This is actually useful because for some bundle workflow you need the reference of the folder for a copy or load the themes.

In this way, it prevents copy the whole folder, but you still have a reference to the folder path in case you need it.

2021-03-23 11:59 UTC, RunDevelopment commented
Why do we need to export this path? Couldn't somebody that needs the path just do `require.resolve('prism-themes/themes')`? It's not like we plan to rename the `themes` folder anytime soon (since that would be a breaking change).

2021-03-23 12:20 UTC, Kikobeats commented
@RunDevelopment that was my initial assumption and it's failling:

https://github.com/microlinkhq/browserless/blob/master/packages/screenshot/src/pretty/theme.js#L9

The assumption is wrong since the folder is going to live depending on where npm install decides to place the folder, meaning that if the project has other dependencies using prism-themes it will be placed in a place where both dependencies can find it, making the path unpredictable.

The solution is to use "main" on `package.json` to point to the dependency path, and because the dependency path is calculated using `__dirname`, you always will have the absolute path!

2021-03-23 12:32 UTC, RunDevelopment commented
@Kikobeats Not `path.resolve` but [`require.resolve`](https://nodejs.org/api/modules.html#modules_require_resolve_request_options).

2021-03-23 14:19 UTC, Kikobeats commented
@RunDevelopment  `require.resolve` can't find the module since the package doesn't have a `"main"` and it can't be found

<img width="666" alt="Screen Shot 2021-03-23 at 15 18 23" src="https://user-images.githubusercontent.com/2096101/112161157-250b3900-8beb-11eb-9d01-4e1fbcfdf650.png">

2021-03-23 14:26 UTC, RunDevelopment commented
`require` wants to find `.js` files, right... my bad. A main module is necessary in that case.

2021-03-23 14:29 UTC, RunDevelopment requested changes
A few minor changes and we can merge this.

Please follow the Prism/prismjs coding style:

- use semicolons
- tabs for indentation

2021-03-23 14:29 UTC, RunDevelopment commented on index.js
> +  folderPath: path.resolve(__dirname, 'themes')
Please rename this to `themesDirectory`.

```suggestion
	themesDirectory: path.resolve(__dirname, 'themes')
```

2021-03-23 14:31 UTC, Kikobeats commented
fixed lint issues!

2021-03-23 14:49 UTC, Kikobeats commented
added missing semicolon

2021-03-23 14:57 UTC, RunDevelopment approved these changes
Green light from my end but I would like to know @mAAdhaTTah's opinion on this.

This sorta changes the nature of this project from pure CSS to CSS + some JS, so I'd like to have a second opinion.

2021-03-24 23:37 UTC, Kikobeats commented
I understand although literally I just added 5 lines of javascript to make possible use it like the rest of npm dependencies

2021-04-30 22:25 UTC, Kikobeats commented
@RunDevelopment any status of this? really want to use the library 😭

2021-05-01 12:04 UTC, RunDevelopment commented
Sorry for the delay @Kikobeats. Let's merge this.

2021-05-01 12:05 UTC, merged

2021-05-01 22:07 UTC, Kikobeats commented
Thanks a lot!

2021-05-01 22:10 UTC, Kikobeats commented
@RunDevelopment thanks a lot! can you please release a new version?

2021-05-04 11:52 UTC, RunDevelopment commented
Just published a new version @Kikobeats.